version: '3'
services:
  database:
    image: 'mariadb:latest'
    container_name: mariadbCont
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hotelC
      MYSQL_ROOT_PASSWORD: root
      ports:
        '3308:3308'
      volumes:
        ${PWD}/mariadb/:/var/lib/mysql/